# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@yasniel1408'
      - name: Configure
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          npm i -g @teambit/bvm
          bvm upgrade -y
          echo 'export PATH=$(npm bin -g):$PATH' >> ~/.bashrc && source ~/.bashrc
          bit install
      - name: Crear etiqueta en Bit
        run: bit tag
      - name: Publicar a npm
        run: bit publish
